# Generated by Django 4.2.6 on 2023-10-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='adminname',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lastname',
            new_name='adminstaffnumber',
        ),
        migrations.AddField(
            model_name='member',
            name='adminemail',
            field=models.EmailField(default='mwajuma@gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='adminphonenumber',
            field=models.CharField(default=254700000000, max_length=15),
        ),
        migrations.AddField(
            model_name='member',
            name='institution',
            field=models.CharField(default='Technical University of Mombasa', max_length=255),
        ),
    ]
