# Generated by Django 4.2.6 on 2023-11-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_member_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admision_number', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('course_of_study', models.CharField(max_length=255)),
                ('duration_of_study', models.CharField(max_length=255)),
                ('mode_of_study', models.CharField(max_length=255)),
            ],
        ),
    ]
